name: Create Release PR
on:
  push:
    branches: [ release-test ]

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: release-test

      - name: Fetch release branch
        run: |
          git remote -v  # Debug: show remotes
          git fetch origin
          git checkout -B release-test origin/release-test
          git log --oneline origin/release..origin/release-test  # Debug: Show commits that differ
          git diff origin/release origin/release-test --stat     # Debug: Show file differences
          git status

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        with:
          extra_plugins: |
            @semantic-release/commit-analyzer
            @semantic-release/release-notes-generator
            @semantic-release/github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: 'chore: Create new release'
          base: release
          branch: release-test
          delete-branch: false
          commit-message: "chore: merge release-test into release"
          author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
          labels: |
            automated pr
          body: |
            Automated PR from release-test to release

      - name: Check outputs
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"