name: Create Release PR
on:
  push:
    branches: [ release-test ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          title: 'chore: Create new release'
          base: release
          body: 'Automated PR from dev to release'

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        with:
          branch: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}