name: Create Release PR
on:
  push:
    branches: [release-test]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: release-test

      - name: Fetch release branch
        run: |
          git fetch origin release:release
          git status

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        with:
          branch: release-test
          extra_plugins: |
            @semantic-release/commit-analyzer
            @semantic-release/release-notes-generator
            @semantic-release/github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Pull Request
        run: |
          echo "Checking differences between branches..."
          git diff release...release-test --name-only

          # Create PR using gh cli
          gh pr create \
            --base release \
            --head release-test \
            --title "chore: Create new release" \
            --body "Automated PR from release-test to release" \
            || echo "PR already exists or no changes to create PR"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
