name: Notify Discord on Bug Label

on:
  issues:
    types: [labeled]

jobs:
  notify_bug:
    runs-on: ubuntu-latest
    steps:
      - name: Send Bug Notification to Discord
        if: github.event.label.name == 'bug'  # Correct placement of 'if'
        run: |
          curl -H "Content-Type: application/json" \
            -X POST \
            -d '{
              "content": "🐞 **Bug Report Created!**\n**Title:** '${{ github.event.issue.title }}'\n**Link:** '${{ github.event.issue.html_url }}'"
            }' \
            ${{ secrets.DISCORD_WEBHOOK_URL }}
